import { useQuery } from "@tanstack/react-query";
import { Clipboard, History, RefreshCw, Search } from "lucide-react";
import { useState } from "react";
import { api } from "../lib/api";
import { formatNumber } from "../lib/format";
import { useAuth } from "../auth/AuthContext";
import { Badge } from "../components/ui/Badge";
import { Card } from "../components/ui/Card";
import { EmptyState, ErrorState, LoadingState } from "../components/ui/Feedback";
import { PageHeader } from "../components/ui/PageHeader";

const labels: Record<string, string> = { login_succeeded: "Login realizado", login_success: "Login realizado", login_failed: "Login falhou", logout: "Logout", sessions_revoked: "Sessões revogadas", user_created: "Usuário criado", user_updated: "Usuário atualizado", user_enabled: "Usuário ativado", user_disabled: "Usuário desativado", password_reset_by_admin: "Senha redefinida", password_changed: "Senha alterada", import_created: "Importação criada", import_duplicate_detected: "Importação duplicada detectada", execution_requested: "Execução solicitada", execution_started: "Execução iniciada", execution_finished: "Execução concluída", execution_failed: "Execução falhou", report_created: "Relatório criado", report_downloaded: "Relatório baixado", group_configuration_updated: "Grupos atualizados" };
function label(action?: string) { return labels[String(action || "")] || action || "Evento"; }
function date(value?: string) { if (!value) return "—"; return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)); }
function short(value?: string | null) { return value ? `${value.slice(0, 8)}…` : "—"; }

export function AuditPage() {
  const auth = useAuth(); const [action, setAction] = useState(""); const [actorType, setActorType] = useState(""); const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["audit-events", action, actorType, page], queryFn: () => api.auditEvents({ action, actorType, page, limit: 25 }), enabled: auth.user?.role === "MASTER_ADMIN", staleTime: 10_000, retry: false });
  if (auth.user?.role !== "MASTER_ADMIN") return <div className="page-stack"><PageHeader eyebrow="AUDITORIA" title="Acesso restrito" description="A auditoria global está disponível somente para o MASTER_ADMIN." /><EmptyState title="Sem permissão" description="Seu perfil não pode consultar a trilha global de auditoria." /></div>;
  return <div className="page-stack"><PageHeader eyebrow="AUDITORIA OPERACIONAL" title="Auditoria" description="Trilha oficial de ações registradas pela Central OS." />
    <Card tone="violet" className="history-hero"><div><span className="history-hero-icon"><History /></span><div><p className="eyebrow">AUDIT_EVENTS</p><h2>Ações rastreáveis</h2><p>Eventos técnicos são apresentados com contexto seguro e IDs resumidos.</p></div></div><Badge tone="info">{formatNumber(query.data?.total || 0)} evento(s)</Badge></Card>
    <Card className="sheet-card"><div className="sheet-toolbar history-filters"><div className="sheet-search"><Search className="h-4 w-4" /><input value={action} onChange={(event) => { setAction(event.target.value); setPage(1); }} placeholder="Filtrar ação técnica..." /></div><select value={actorType} onChange={(event) => { setActorType(event.target.value); setPage(1); }} aria-label="Filtrar ator"><option value="">Todos os atores</option><option value="USER">Usuário</option><option value="SYSTEM">Sistema</option><option value="WHATSAPP">WhatsApp</option><option value="ADMIN_TOOL">Ferramenta administrativa</option></select><button className="icon-button" onClick={() => query.refetch()} aria-label="Atualizar auditoria"><RefreshCw className="h-4 w-4" /></button></div><div className="sheet-frame">{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={(query.error as Error).message} /> : !(query.data?.items || []).length ? <EmptyState title="Nenhum evento de auditoria" description="As ações relevantes aparecerão aqui." /> : <table className="modern-table"><thead><tr><th>Data</th><th>Ação</th><th>Ator</th><th>Entidade</th><th>Resultado</th><th>Contexto</th></tr></thead><tbody>{query.data?.items.map(event => <tr key={event.id}><td>{date(event.createdAt)}</td><td><strong>{label(event.action)}</strong><small className="history-duplicate-inline">{event.action}</small></td><td>{event.actorName || event.actorType || "—"}</td><td>{event.entityType || "—"} <small>{short(event.entityId)}</small></td><td><Badge tone={event.result === "failure" ? "danger" : event.result === "info" ? "info" : "success"}>{event.result || "—"}</Badge></td><td><span title={JSON.stringify(event.metadata || {})}><Clipboard className="h-3 w-3" /> {Object.keys(event.metadata || {}).length} campo(s)</span></td></tr>)}</tbody></table>}</div><div className="history-pagination"><span>Página {query.data?.page || page} de {query.data?.totalPages || 1}</span><button className="outline-action" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Anterior</button><button className="outline-action" disabled={page >= (query.data?.totalPages || 1)} onClick={() => setPage(value => value + 1)}>Próxima</button></div></Card>
  </div>;
}
