import { localApiFetch } from "/local-api.js";
const body=document.getElementById("analysisBody"), search=document.getElementById("tableSearch"), badge=document.getElementById("resultCount"), days=document.getElementById("days");
const view=document.body.dataset.view||"analisadas"; let all=[];
const escape=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const label=v=>({possivelmente_realizada:"Possivelmente fechada",possivelmente_pendente:"Pendente",revisao_manual:"Em análise",sem_evidencia:"Sem evidência",nao_localizada:"Não localizada"}[v]||v||"—");
function filtered(items){ if(view==="localizadas")return items.filter(x=>x.classification!=="nao_localizada");if(view==="nao-localizadas")return items.filter(x=>x.classification==="nao_localizada");if(view==="fechadas")return items.filter(x=>x.classification==="possivelmente_realizada");if(view==="pendentes")return items.filter(x=>!["nao_localizada","possivelmente_realizada"].includes(x.classification));return items; }
function render(){const q=(search?.value||"").toLowerCase();const rows=all.filter(x=>!q||[x.client,x.reference?.client,x.sender,x.groupName,label(x.classification)].join(" ").toLowerCase().includes(q));badge.textContent=`${rows.length} OS`;body.innerHTML=rows.length?rows.map(x=>{const c=x.client||x.reference?.client||"—";const ev=(x.evidence||[])[0]?.text||x.originalText||"";return `<tr><td><strong>${escape(c)}</strong></td><td>${escape(x.sender||"—")}</td><td><span class="status-pill">${escape(label(x.classification))}</span></td><td>${escape(x.groupName||"—")}</td><td>${escape(ev.slice(0,220)||"Sem evidência")}</td></tr>`}).join(""):'<tr><td colspan="5"><div class="empty">Nenhuma OS nesta visão.</div></td></tr>';}
async function load(){body.innerHTML='<tr><td colspan="5"><div class="empty">Carregando análise…</div></td></tr>';try{const d=await localApiFetch(`/api/analise?days=${days?.value||30}`);all=filtered(d.items||[]);render();}catch(e){body.innerHTML=`<tr><td colspan="5"><div class="empty">${escape(e.message)}</div></td></tr>`;badge.textContent="Indisponível";}}
search?.addEventListener("input",render);days?.addEventListener("change",load);document.getElementById("refresh")?.addEventListener("click",load);load();
